# Generated by Django 5.2 on 2025-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationcode",
            name="code",
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="last_code_generated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
