# Generated by Django 5.1.11 on 2025-08-05 09:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivity',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.classsession'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolinvitation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='target_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schoolinvitation'),
        ),
        migrations.AddField(
            model_name='schoolinvitationlink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitation_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolinvitationlink',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='educational_system',
            field=models.ForeignKey(default=1, help_text='Educational system used by this school', on_delete=django.db.models.deletion.PROTECT, related_name='schools_using_system', to='accounts.educationalsystem', verbose_name='educational system'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='educational_system',
            field=models.ForeignKey(default=1, help_text='Educational system this student belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.educationalsystem'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(help_text='Course for which progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_records', to='accounts.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='school',
            field=models.ForeignKey(help_text='School where progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_records', to='accounts.school', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(help_text='Student whose progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='progressassessment',
            name='student_progress',
            field=models.ForeignKey(help_text='Progress record this assessment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.studentprogress', verbose_name='student progress'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='teacherinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_teacher_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherinvitation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invitations', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='teacher',
            field=models.ForeignKey(help_text="Teacher tracking this student's progress", on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_records', to='accounts.teacherprofile', verbose_name='teacher'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'is_used'], name='accounts_ve_email_7e3f97_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'created_at'], name='accounts_ve_email_87ad10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'educational_system')},
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['school', '-timestamp'], name='accounts_sc_school__0e0c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['school', 'activity_type', '-timestamp'], name='accounts_sc_school__727125_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['actor', '-timestamp'], name='accounts_sc_actor_i_04515d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolinvitationlink',
            unique_together={('school', 'role')},
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['school', 'role', 'is_active'], name='accounts_sc_school__05ee6d_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['school', 'joined_at'], name='accounts_sc_school__f1da9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolmembership',
            unique_together={('user', 'school', 'role')},
        ),
        migrations.AddIndex(
            model_name='schoolsettings',
            index=models.Index(fields=['school'], name='accounts_sc_school__c9d7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsettings',
            index=models.Index(fields=['educational_system'], name='accounts_sc_educati_795fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsettings',
            index=models.Index(fields=['language'], name='accounts_sc_languag_48f62c_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsettings',
            index=models.Index(fields=['timezone'], name='accounts_sc_timezon_5b4855_idx'),
        ),
        migrations.AddIndex(
            model_name='progressassessment',
            index=models.Index(fields=['student_progress', '-assessment_date'], name='accounts_pr_student_b4c179_idx'),
        ),
        migrations.AddIndex(
            model_name='progressassessment',
            index=models.Index(fields=['assessment_type', '-assessment_date'], name='accounts_pr_assessm_6a53d6_idx'),
        ),
        migrations.AddIndex(
            model_name='progressassessment',
            index=models.Index(fields=['is_graded', '-assessment_date'], name='accounts_pr_is_grad_096ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='progressassessment',
            index=models.Index(fields=['assessment_date'], name='accounts_pr_assessm_33867a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['school', 'status', '-created_at'], name='accounts_te_school__92f957_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['batch_id', '-created_at'], name='accounts_te_batch_i_206901_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['email', 'school', 'is_accepted'], name='accounts_te_email_1bae7a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['token'], name='accounts_te_token_7c3b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['expires_at', 'is_accepted'], name='accounts_te_expires_445f20_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherinvitation',
            index=models.Index(fields=['email_delivery_status', 'retry_count'], name='accounts_te_email_d_35fa71_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 8, 5, 9, 24, 38, 825311, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['profile_completion_score'], name='accounts_te_profile_66b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete'], name='accounts_te_is_prof_f392a7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['last_profile_update'], name='accounts_te_last_pr_e9feb6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['last_activity'], name='accounts_te_last_ac_156d12_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['specialty'], name='accounts_te_special_67ff46_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['hourly_rate'], name='accounts_te_hourly__9a19a0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete', '-profile_completion_score'], name='accounts_te_is_prof_929d56_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete', 'hourly_rate'], name='accounts_te_is_prof_98b8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['hourly_rate'], name='accounts_te_hourly__c3061c_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['is_active', 'hourly_rate'], name='accounts_te_is_acti_8eb952_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['course', 'is_active'], name='accounts_te_course__42098d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['teacher', 'is_active'], name='accounts_te_teacher_f9bf5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher', 'course')},
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'course'], name='accounts_st_student_c3cfb7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['teacher', '-updated_at'], name='accounts_st_teacher_99c5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['school', 'course'], name='accounts_st_school__8f60be_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['completion_percentage'], name='accounts_st_complet_91605f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['current_level'], name='accounts_st_current_168bda_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprogress',
            constraint=models.UniqueConstraint(fields=('student', 'teacher', 'course'), name='unique_student_teacher_course_progress'),
        ),
    ]
