# Generated by Django 5.2 on 2025-05-03 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_emailverificationcode_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailVerificationCode",
            new_name="VerificationCode",
        ),
    ]
