# Generated by Django 5.2 on 2025-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
