# Generated by Django 5.1.11 on 2025-08-08 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_educational_systems'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='buffer_time_group',
            field=models.PositiveIntegerField(default=20, help_text='Buffer time in minutes for group classes', verbose_name='buffer time for group classes'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='buffer_time_trial',
            field=models.PositiveIntegerField(default=10, help_text='Buffer time in minutes for trial classes', verbose_name='buffer time for trial classes'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='default_buffer_time_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Default buffer time between classes in minutes', verbose_name='default buffer time minutes'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='default_max_daily_bookings',
            field=models.PositiveIntegerField(default=8, help_text='Default maximum classes per day for teachers', verbose_name='default max daily bookings'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='default_max_weekly_bookings',
            field=models.PositiveIntegerField(default=30, help_text='Default maximum classes per week for teachers', verbose_name='default max weekly bookings'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='default_minimum_notice_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Default minimum notice period in minutes (2 hours)', verbose_name='default minimum notice minutes'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='student_max_daily_bookings',
            field=models.PositiveIntegerField(default=3, help_text='Maximum classes per day for students', verbose_name='student max daily bookings'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='student_max_weekly_bookings',
            field=models.PositiveIntegerField(default=10, help_text='Maximum classes per week for students', verbose_name='student max weekly bookings'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Buffer time between classes in minutes (school default if null)', null=True, verbose_name='buffer time minutes'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_daily_bookings',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum classes per day (school default if null)', null=True, verbose_name='maximum daily bookings'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_weekly_bookings',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum classes per week (school default if null)', null=True, verbose_name='maximum weekly bookings'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='minimum_notice_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Override minimum notice period in minutes (school default if null)', null=True, verbose_name='minimum notice minutes'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 8, 8, 0, 49, 57, 484634, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
