# Generated by Django 5.2 on 2025-06-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_emailverificationcode_verificationcode"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["email", "is_used"], name="accounts_ve_email_7e3f97_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["email", "created_at"], name="accounts_ve_email_87ad10_idx"),
        ),
    ]
