# Generated by Django 5.2 on 2025-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_emailverificationcode_failed_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="secret_key",
            field=models.CharField(default="DEFAULTSECRETKEYTOBEREPLACED", max_length=32),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
