# Generated by Django 5.2 on 2025-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_emailverificationcode_secret_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("manager", "School Manager"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                default="manager",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
