# Generated by Django 5.2 on 2025-06-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_verificationcode_accounts_ve_email_7e3f97_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="course name")),
                (
                    "code",
                    models.CharField(
                        help_text="Alphanumeric code for the course (e.g., educational system codes)",
                        max_length=20,
                        unique=True,
                        verbose_name="course code",
                    ),
                ),
                (
                    "educational_system",
                    models.CharField(
                        default="custom",
                        help_text="Educational system this course belongs to (e.g., 'portugal', 'custom')",
                        max_length=50,
                        verbose_name="educational system",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        default="other",
                        help_text="Education level (e.g., 'ensino_secundario', 'ensino_basico', 'other')",
                        max_length=50,
                        verbose_name="education level",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the course content and objectives",
                        verbose_name="course description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("code", "educational_system")},
            },
        ),
        migrations.CreateModel(
            name="TeacherCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Specific hourly rate for this course (overrides teacher's default rate)",
                        max_digits=6,
                        null=True,
                        verbose_name="hourly rate for this course",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is actively teaching"),
                ),
                (
                    "started_teaching",
                    models.DateField(auto_now_add=True, verbose_name="started teaching date"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_teachers",
                        to="accounts.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_courses",
                        to="accounts.teacherprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "course")},
            },
        ),
    ]
