# Generated by Django 5.2 on 2025-06-06 13:45

from django.db import migrations


def create_portuguese_high_school_courses(apps, schema_editor):
    """
    Create Portuguese high school courses as independent entities.
    """
    # Get the Course model from migration state
    Course = apps.get_model("accounts", "Course")

    # Portuguese high school courses with their codes from the provided list
    portugal_courses = [
        ("138", "Português Língua Segunda"),
        ("501", "Alemão"),
        ("517", "Francês"),
        ("547", "Espanhol"),
        ("550", "Inglês"),
        ("623", "História A"),
        ("635", "Matemática A"),
        ("639", "Português"),
        ("702", "Biologia e Geologia"),
        ("706", "Desenho A"),
        ("708", "Geometria Descritiva A"),
        ("712", "Economia A"),
        ("714", "Filosofia"),
        ("715", "Física e Química A"),
        ("719", "Geografia A"),
        ("723", "História B"),
        ("724", "História da Cultura das Artes"),
        ("732", "Latim A"),
        ("734", "Literatura Portuguesa"),
        ("735", "Matemática B"),
        ("835", "Matemática Aplicada às Ciências Sociais"),
        ("839", "Português Língua Não Materna"),
        ("847", "Espanhol"),
        ("848", "Mandarim"),
        ("849", "Italiano"),
    ]

    # Create course entries
    for code, name in portugal_courses:
        Course.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "educational_system": "portugal",
                "education_level": "ensino_secundario",
                "description": f"Curso do ensino secundário português: {name}",
            },
        )


def reverse_portuguese_high_school_courses(apps, schema_editor):
    """
    Remove Portuguese high school courses.
    """
    Course = apps.get_model("accounts", "Course")

    # Remove courses
    Course.objects.filter(
        educational_system="portugal", education_level="ensino_secundario"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_restructure_course_models"),
    ]

    operations = [
        migrations.RunPython(
            create_portuguese_high_school_courses,
            reverse_portuguese_high_school_courses,
        ),
    ]
