# Generated by Django 5.2 on 2025-04-22 09:56

import pyotp
from django.db import migrations


def generate_new_secrets(apps, schema_editor):
    """
    Replace default secrets with unique ones for all existing verification records.
    """
    EmailVerificationCode = apps.get_model("accounts", "EmailVerificationCode")

    # Find all records with the default secret or empty secrets
    default_records = EmailVerificationCode.objects.filter(
        secret_key="DEFAULTSECRETKEYTOBEREPLACED"
    )

    # Update each record with a new random secret
    for record in default_records:
        record.secret_key = pyotp.random_base32()
        record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_new_secrets, migrations.RunPython.noop),
    ]
