# Generated by Django 5.2 on 2025-04-22 09:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_fix_verification_secrets"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="secret_key",
            field=models.CharField(max_length=32),
        ),
    ]
