# Generated by Django 5.2 on 2025-06-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_populate_portuguese_high_school_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolInvitationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("school_owner", "School Owner"),
                            ("school_admin", "School Administrator"),
                            ("teacher", "Teacher"),
                            ("school_staff", "School Staff"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True, verbose_name="token")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("usage_count", models.PositiveIntegerField(default=0, verbose_name="usage count")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited uses",
                        null=True,
                        verbose_name="max uses",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitation_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_links",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "role")},
            },
        ),
    ]
