# Generated by Django 5.1.11 on 2025-08-05 19:46

from django.db import migrations


def create_default_educational_system(apps, schema_editor):
    """Create default educational system required by SchoolSettings."""
    EducationalSystem = apps.get_model('accounts', 'EducationalSystem')
    
    # Create default Portugal educational system with id=1
    EducationalSystem.objects.get_or_create(
        id=1,
        defaults={
            'name': 'Portugal',
            'code': 'pt',
            'description': 'Portuguese educational system',
            'is_active': True
        }
    )


def reverse_default_educational_system(apps, schema_editor):
    """Remove default educational system."""
    EducationalSystem = apps.get_model('accounts', 'EducationalSystem')
    try:
        EducationalSystem.objects.get(id=1).delete()
    except EducationalSystem.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_educational_system,
            reverse_default_educational_system
        ),
    ]
