# Generated by Django 5.2 on 2025-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_schoolinvitationlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the educational system (e.g., 'Portugal', 'Brazil')",
                        max_length=100,
                        verbose_name="system name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the system (e.g., 'pt', 'br')",
                        max_length=20,
                        unique=True,
                        verbose_name="system code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the educational system",
                        verbose_name="description",
                    ),
                ),
                (
                    "school_years",
                    models.JSONField(
                        default=list,
                        help_text="List of available school years in this system (e.g., ['1º ano', '2º ano', ...])",
                        verbose_name="school years",
                    ),
                ),
                (
                    "education_levels",
                    models.JSONField(
                        default=list,
                        help_text="List of education levels (e.g., ['ensino_basico', 'ensino_secundario'])",
                        verbose_name="education levels",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Educational System",
                "verbose_name_plural": "Educational Systems",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="Alphanumeric code for the course (e.g., educational system codes)",
                max_length=20,
                verbose_name="course code",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="educational_system",
            field=models.CharField(
                default="portugal",
                help_text="Educational system this course belongs to (e.g., 'portugal', 'custom')",
                max_length=50,
                verbose_name="educational system",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Street, number, postal code and location",
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="school_year",
            field=models.CharField(
                help_text="School year within the educational system",
                max_length=50,
                verbose_name="school year",
            ),
        ),
    ]
