# Generated by Django 5.1.11 on 2025-08-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more'),
        ('accounts', '0008_add_default_educational_system'),
    ]

    operations = [
    ]
