# Generated by Django 5.2 on 2025-06-09 10:28

from django.db import migrations


def populate_educational_systems(apps, schema_editor):
    """Populate initial educational systems"""
    EducationalSystem = apps.get_model("accounts", "EducationalSystem")

    # Portugal Education System (ID 1 - DEFAULT)
    EducationalSystem.objects.create(
        id=1,
        name="Portugal",
        code="pt",
        description="Portuguese education system",
        school_years=[
            ["1", "1º ano"],
            ["2", "2º ano"],
            ["3", "3º ano"],
            ["4", "4º ano"],  # 1st cycle (1-4)
            ["5", "5º ano"],
            ["6", "6º ano"],  # 2nd cycle (5-6)
            ["7", "7º ano"],
            ["8", "8º ano"],
            ["9", "9º ano"],  # 3rd cycle (7-9)
            ["10", "10º ano"],
            ["11", "11º ano"],
            ["12", "12º ano"],  # Secondary (10-12)
        ],
        education_levels=[
            "ensino_basico_1_ciclo",  # 1st to 4th grade
            "ensino_basico_2_ciclo",  # 5th to 6th grade
            "ensino_basico_3_ciclo",  # 7th to 9th grade
            "ensino_secundario",  # 10th to 12th grade
        ],
        is_active=True,
    )

    # Generic/Custom Education System
    EducationalSystem.objects.create(
        id=2,
        name="Custom",
        code="custom",
        description="Generic education system for custom configurations",
        school_years=[
            ["1", "Grade 1"],
            ["2", "Grade 2"],
            ["3", "Grade 3"],
            ["4", "Grade 4"],
            ["5", "Grade 5"],
            ["6", "Grade 6"],
            ["7", "Grade 7"],
            ["8", "Grade 8"],
            ["9", "Grade 9"],
            ["10", "Grade 10"],
            ["11", "Grade 11"],
            ["12", "Grade 12"],
        ],
        education_levels=["elementary", "middle_school", "high_school"],
        is_active=True,
    )

    # Brazil Education System
    EducationalSystem.objects.create(
        id=3,
        name="Brazil",
        code="br",
        description="Brazilian education system",
        school_years=[
            ["1ef", "1º ano EF"],
            ["2ef", "2º ano EF"],
            ["3ef", "3º ano EF"],
            ["4ef", "4º ano EF"],
            ["5ef", "5º ano EF"],  # Elementary I
            ["6ef", "6º ano EF"],
            ["7ef", "7º ano EF"],
            ["8ef", "8º ano EF"],
            ["9ef", "9º ano EF"],  # Elementary II
            ["1em", "1º ano EM"],
            ["2em", "2º ano EM"],
            ["3em", "3º ano EM"],  # High School
        ],
        education_levels=[
            "ensino_fundamental_anos_iniciais",  # 1st to 5th grade
            "ensino_fundamental_anos_finais",  # 6th to 9th grade
            "ensino_medio",  # High school
        ],
        is_active=True,
    )


def reverse_populate_educational_systems(apps, schema_editor):
    """Remove the created educational systems"""
    EducationalSystem = apps.get_model("accounts", "EducationalSystem")
    EducationalSystem.objects.filter(code__in=["pt", "custom", "br"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_create_educational_system_model"),
    ]

    operations = [
        migrations.RunPython(populate_educational_systems, reverse_populate_educational_systems),
    ]
