# Generated by Django 5.2 on 2025-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_school_rename_student_studentprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="phone verified"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="primary_contact",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone")],
                default="email",
                max_length=10,
                verbose_name="primary contact",
            ),
        ),
    ]
