# Generated by Django 5.2 on 2025-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_populate_educational_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="educational_system",
            field=models.ForeignKey(
                default=1,
                help_text="Educational system this student belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="accounts.educationalsystem",
            ),
        ),
    ]
