# Generated by Django 5.2 on 2025-06-09 10:30

from django.db import migrations


def migrate_course_educational_systems(apps, schema_editor):
    """Migrate existing courses from string to foreign key"""
    Course = apps.get_model("accounts", "Course")
    EducationalSystem = apps.get_model("accounts", "EducationalSystem")

    # Get the systems
    portugal_system = EducationalSystem.objects.get(code="pt")
    custom_system = EducationalSystem.objects.get(code="custom")

    # Update courses to use the new foreign key structure
    # Use raw SQL since we're working with mixed field types
    db_alias = schema_editor.connection.alias

    # Update all courses that have educational_system='portugal' to use portugal system (id=1)
    schema_editor.execute(
        "UPDATE accounts_course SET educational_system = %s WHERE educational_system = 'portugal'",
        [str(portugal_system.id)],
    )

    # Update all other courses to use custom system (id=2)
    schema_editor.execute(
        "UPDATE accounts_course SET educational_system = %s WHERE educational_system != %s",
        [str(custom_system.id), str(portugal_system.id)],
    )


def reverse_migrate_course_educational_systems(apps, schema_editor):
    """Reverse the course migration"""
    Course = apps.get_model("accounts", "Course")
    EducationalSystem = apps.get_model("accounts", "EducationalSystem")

    # Convert back to string format using raw SQL
    portugal_system = EducationalSystem.objects.get(code="pt")
    custom_system = EducationalSystem.objects.get(code="custom")

    schema_editor.execute(
        "UPDATE accounts_course SET educational_system = 'portugal' WHERE educational_system = %s",
        [str(portugal_system.id)],
    )

    schema_editor.execute(
        "UPDATE accounts_course SET educational_system = 'custom' WHERE educational_system = %s",
        [str(custom_system.id)],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_add_educational_system_to_student"),
    ]

    operations = [
        migrations.RunPython(
            migrate_course_educational_systems, reverse_migrate_course_educational_systems
        ),
    ]
