# Generated by Django 5.2 on 2025-06-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_migrate_course_educational_system_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="educational_system",
            field=models.ForeignKey(
                help_text="Educational system this course belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="accounts.educationalsystem",
            ),
        ),
    ]
