# Generated by Django 5.2 on 2025-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_convert_course_educational_system_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalsystem',
            name='education_levels',
        ),
        migrations.RemoveField(
            model_name='educationalsystem',
            name='school_years',
        ),
        migrations.AlterField(
            model_name='course',
            name='education_level',
            field=models.CharField(default='other', help_text='Education level within the educational system', max_length=50, verbose_name='education level'),
        ),
        migrations.AlterField(
            model_name='educationalsystem',
            name='code',
            field=models.CharField(choices=[('pt', 'Portugal'), ('custom', 'Custom'), ('br', 'Brazil')], help_text="Unique code for the system (e.g., 'pt', 'br')", max_length=20, unique=True, verbose_name='system code'),
        ),
    ]
