# Generated by Django 5.2 on 2025-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_convert_to_enumeration_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_login_completed",
            field=models.BooleanField(default=False, verbose_name="first login completed"),
        ),
    ]
