# Generated by Django 5.2 on 2025-07-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_school_dashboard_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivity',
            name='activity_type',
            field=models.CharField(choices=[('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_declined', 'Invitation Declined'), ('student_joined', 'Student Joined'), ('teacher_joined', 'Teacher Joined'), ('class_created', 'Class Created'), ('class_completed', 'Class Completed'), ('class_cancelled', 'Class Cancelled'), ('settings_updated', 'Settings Updated')], max_length=30),
        ),
    ]
