# Generated by Django 5.2 on 2025-07-28 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_create_teacher_invitation_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='onboarding completed'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_progress',
            field=models.JSONField(blank=True, default=dict, verbose_name='onboarding progress'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tutorial_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='tutorial preferences'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 7, 28, 13, 7, 31, 823600, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
