# Generated by Django 5.2 on 2025-07-28 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_onboarding_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education_background',
            field=models.JSONField(blank=True, default=dict, help_text='Structured educational background data (degree, institution, field, year)', verbose_name='education background'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether the profile meets completion requirements', verbose_name='is profile complete'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='When the teacher was last active in the system', null=True, verbose_name='last activity'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True, help_text='When the profile was last updated', verbose_name='last profile update'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_completion_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated profile completion percentage (0-100)', max_digits=5, verbose_name='profile completion score'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rate_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed rate structure for different class types', verbose_name='rate structure'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subjects the teacher specializes in', verbose_name='teaching subjects'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='weekly_availability',
            field=models.JSONField(blank=True, default=dict, help_text='Structured weekly availability schedule', verbose_name='weekly availability'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['profile_completion_score'], name='accounts_te_profile_66b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete'], name='accounts_te_is_prof_f392a7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['last_profile_update'], name='accounts_te_last_pr_e9feb6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['last_activity'], name='accounts_te_last_ac_156d12_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 7, 28, 16, 17, 53, 109581, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
