# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_enhance_teacher_profile'),
    ]

    operations = [
        # Add new fields to School model
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Primary brand color in hex format', max_length=7, verbose_name='primary color'),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(blank=True, default='#1F2937', help_text='Secondary brand color in hex format', max_length=7, verbose_name='secondary color'),
        ),
        migrations.AddField(
            model_name='school',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Official email domain for the school', max_length=100, verbose_name='email domain'),
        ),
        
        # Enhance SchoolSettings model with comprehensive configuration options
        migrations.AddField(
            model_name='schoolsettings',
            name='educational_system',
            field=models.ForeignKey(default=1, help_text='Educational system used by this school', on_delete=django.db.models.deletion.PROTECT, related_name='schools_using_system', to='accounts.educationalsystem', verbose_name='educational system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='grade_levels',
            field=models.JSONField(blank=True, default=list, help_text='List of grade levels offered by this school', verbose_name='grade levels'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='billing_contact_name',
            field=models.CharField(blank=True, help_text='Name of billing contact person', max_length=100, verbose_name='billing contact name'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='billing_contact_email',
            field=models.EmailField(blank=True, help_text='Email for billing-related communications', max_length=254, verbose_name='billing contact email'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address for invoices and payments', verbose_name='billing address'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number for billing', max_length=50, verbose_name='tax ID'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound')], default='EUR', help_text='Default currency for pricing and billing', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='pt', help_text='Default language for the school interface', max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='working_hours_start',
            field=models.TimeField(default='08:00', help_text='School working hours start time', verbose_name='working hours start'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='working_hours_end',
            field=models.TimeField(default='18:00', help_text='School working hours end time', verbose_name='working hours end'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='working_days',
            field=models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)', verbose_name='working days'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable email notifications for school events', verbose_name='email notifications enabled'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications for school events', verbose_name='SMS notifications enabled'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='allow_student_self_enrollment',
            field=models.BooleanField(default=False, help_text='Allow students to enroll themselves', verbose_name='allow student self-enrollment'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='require_parent_approval',
            field=models.BooleanField(default=True, help_text='Require parental approval for student actions', verbose_name='require parent approval'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='auto_assign_teachers',
            field=models.BooleanField(default=False, help_text='Automatically assign available teachers to classes', verbose_name='auto assign teachers'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='class_reminder_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before class to send reminder notifications', verbose_name='class reminder hours'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_calendar_integration',
            field=models.BooleanField(default=False, help_text='Enable integration with external calendar systems', verbose_name='enable calendar integration'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='calendar_integration_type',
            field=models.CharField(blank=True, choices=[('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('caldav', 'CalDAV')], help_text='Type of calendar integration', max_length=20, verbose_name='calendar integration type'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_email_integration',
            field=models.BooleanField(default=False, help_text='Enable integration with external email systems', verbose_name='enable email integration'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_integration_provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', 'Custom SMTP')], help_text='Email integration provider', max_length=20, verbose_name='email integration provider'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='data_retention_policy',
            field=models.CharField(choices=[('1_year', '1 Year'), ('2_years', '2 Years'), ('5_years', '5 Years'), ('indefinite', 'Indefinite')], default='2_years', help_text='How long to retain student and class data', max_length=20, verbose_name='data retention policy'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='gdpr_compliance_enabled',
            field=models.BooleanField(default=True, help_text='Enable GDPR compliance features', verbose_name='GDPR compliance enabled'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='allow_data_export',
            field=models.BooleanField(default=True, help_text='Allow users to export their personal data', verbose_name='allow data export'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='require_data_processing_consent',
            field=models.BooleanField(default=True, help_text='Require explicit consent for data processing', verbose_name='require data processing consent'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]