# Generated by Django 5.2 on 2025-07-28 18:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_enhance_school_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolsettings",
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="educational_system",
            field=models.ForeignKey(
                default=1,
                help_text="Educational system used by this school",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schools_using_system",
                to="accounts.educationalsystem",
                verbose_name="educational system",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsettings",
            index=models.Index(
                fields=["school"], name="accounts_sc_school__c9d7fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsettings",
            index=models.Index(
                fields=["educational_system"], name="accounts_sc_educati_795fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsettings",
            index=models.Index(
                fields=["language"], name="accounts_sc_languag_48f62c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsettings",
            index=models.Index(
                fields=["timezone"], name="accounts_sc_timezon_5b4855_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            7,
                            28,
                            18,
                            36,
                            42,
                            172155,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
