# Generated by Django 5.2 on 2025-07-31 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_tutor_discovery_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['hourly_rate'], name='accounts_te_hourly__c3061c_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['is_active', 'hourly_rate'], name='accounts_te_is_acti_8eb952_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['course', 'is_active'], name='accounts_te_course__42098d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercourse',
            index=models.Index(fields=['teacher', 'is_active'], name='accounts_te_teacher_f9bf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['specialty'], name='accounts_te_special_67ff46_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['hourly_rate'], name='accounts_te_hourly__9a19a0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete', '-profile_completion_score'], name='accounts_te_is_prof_929d56_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_profile_complete', 'hourly_rate'], name='accounts_te_is_prof_98b8fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 7, 31, 14, 8, 15, 387233, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
