# Generated by Django 5.2 on 2025-07-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more'),
    ]

    operations = [
        # Add missing fields to TeacherProfile for comprehensive profile creation
        migrations.AddField(
            model_name='teacherprofile',
            name='grade_level_preferences',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of preferred grade levels (elementary, middle, high school, university)',
                verbose_name='grade level preferences'
            ),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_experience',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured teaching experience data (years, institutions, specializations)',
                verbose_name='teaching experience'
            ),
        ),
        # Add profile photo field to CustomUser
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='profile_photos/',
                help_text='User profile photo',
                verbose_name='profile photo'
            ),
        ),
        # Add credentials storage field for document uploads
        migrations.AddField(
            model_name='teacherprofile',
            name='credentials_documents',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of uploaded credential document references',
                verbose_name='credentials documents'
            ),
        ),
        # Add availability schedule field (more structured than weekly_availability)
        migrations.AddField(
            model_name='teacherprofile',
            name='availability_schedule',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Detailed availability schedule with time slots and preferences',
                verbose_name='availability schedule'
            ),
        ),
    ]
