# Generated by Django 5.2 on 2025-08-01 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddField(
            model_name='teacherinvitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation was declined', null=True, verbose_name='declined at'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 8, 1, 7, 41, 6, 614753, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
