# Generated by Django 5.2 on 2025-08-01 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_emailcommunication_emailsequence_emailsequencestep_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AlterField(
            model_name='emailcommunication',
            name='template_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('welcome', 'Welcome'), ('profile_reminder', 'Profile Reminder'), ('completion_celebration', 'Completion Celebration'), ('ongoing_support', 'Ongoing Support'), ('low_balance_alert', 'Low Balance Alert'), ('package_expiring_alert', 'Package Expiring Alert')], help_text='Type of email template used', max_length=50, verbose_name='template type'),
        ),
        migrations.AlterField(
            model_name='schoolemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('welcome', 'Welcome'), ('profile_reminder', 'Profile Reminder'), ('completion_celebration', 'Completion Celebration'), ('ongoing_support', 'Ongoing Support'), ('low_balance_alert', 'Low Balance Alert'), ('package_expiring_alert', 'Package Expiring Alert')], help_text='Type of email template', max_length=50, verbose_name='template type'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 8, 1, 17, 39, 35, 843516, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
