# Generated by Django 5.1.7 on 2025-03-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('group_class', models.BooleanField(default=False, verbose_name='group class')),
                ('default_duration', models.PositiveIntegerField(default=60, verbose_name='default duration (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'class type',
                'verbose_name_plural': 'class types',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20, verbose_name='status')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Calendar ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('students', models.ManyToManyField(related_name='learning_sessions', to=settings.AUTH_USER_MODEL, verbose_name='students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.classtype', verbose_name='class type')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'class session',
                'verbose_name_plural': 'class sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
