# Generated by Django 5.1.7 on 2025-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classtype",
            name="default_duration",
        ),
        migrations.RemoveField(
            model_name="classtype",
            name="group_class",
        ),
        migrations.AlterField(
            model_name="classtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
