# Generated by Django 5.1.11 on 2025-08-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_balance', 'Low Balance'), ('package_expiring', 'Package Expiring'), ('balance_depleted', 'Balance Depleted')], help_text='Type of notification', max_length=20, verbose_name='notification type')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Notification message content', verbose_name='message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read', verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True, verbose_name='read at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data in JSON format', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Purchase transaction related to this notification (for package expiration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='finances.purchasetransaction', verbose_name='related transaction')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
