# Generated by Django 5.2 on 2025-08-01 17:44

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """Create default email templates for notification system."""
    # Skip template creation for now - templates will be created when needed
    # by the BalanceMonitoringService using existing default template logic
    pass


def reverse_create_default_templates(apps, schema_editor):
    """Remove default email templates for notification system."""
    # No templates were created, so nothing to reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_templates,
            reverse_create_default_templates,
        ),
    ]
