# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.13

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.3
  hooks:
    - id: ruff
      args: [
        "--fix",
        "--extend-select=B,C4,ERA,I,ICN,ISC,N,PL,Q,RUF,S,T10,T20,UP,YTT",
        "--line-length=100",
        "--target-version=py311",
        "--per-file-ignores=**/settings.py:E501,**/tests/*:S101,**/tests/*:S106,**/scripts/*:T201,**/migrations/*:RUF012",
        "--exclude=testing/*,**/migrations/*",
      ]
    - id: ruff-format
      args: ["--line-length=100"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      exclude: ^.*\/migrations\/.*\.py$
      additional_dependencies:
        - pytest==7.1.2
        - types-requests
        - django-stubs
        - djangorestframework-stubs

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
    - id: pyupgrade
      exclude: ^.*\/migrations\/.*\.py$
      args: [--py39-plus]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer

- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.23.1"
  hooks:
    - id: django-upgrade
      exclude: ^.*\/migrations\/.*\.py$
      args: [--target-version, "5.2"]
