[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn aprendecomigo.asgi:application --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[build.nixpacksOptions]
env = {PYTHONPATH = "/app:$PYTHONPATH"}