name: Bug Report
description: Report a bug or unexpected behavior in the Aprende Comigo platform
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much information as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: affected_platform
    attributes:
      label: Affected Platform
      description: Which platform(s) are affected by this bug?
      multiple: true
      options:
        - Web Application
        - iOS App
        - Android App
        - Backend API
        - Admin Dashboard
    validations:
      required: true

  - type: dropdown
    id: user_role
    attributes:
      label: User Role
      description: Which user role were you using when the bug occurred?
      options:
        - School Owner
        - Teacher
        - Student
        - Parent
        - System Admin
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I try to..., the system..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The system should..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Instead, the system..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor inconvenience
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser/App Version
      description: If web, which browser and version? If mobile app, which version?
      placeholder: "Chrome 120.0, iOS App v1.2.3"

  - type: input
    id: school_id
    attributes:
      label: School ID (if applicable)
      description: If this issue is specific to a school, please provide the School ID
      placeholder: "SCH-123456"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add any screenshots or videos that help explain the problem
      placeholder: "Drag and drop images here or paste links"

  - type: textarea
    id: console_errors
    attributes:
      label: Console Errors
      description: If available, please provide any console errors
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after..."

  - type: checkboxes
    id: data_impact
    attributes:
      label: Data Impact
      description: Check all that apply
      options:
        - label: This bug causes data loss
        - label: This bug affects payment processing
        - label: This bug affects student records
        - label: This bug affects scheduling