blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability (Critical)
    url: mailto:security@aprendecomigo.com
    about: For critical security vulnerabilities, please email us directly instead of creating a public issue
  - name: Community Support
    url: https://community.aprendecomigo.com
    about: Ask questions and get help from the community
  - name: Documentation
    url: https://docs.aprendecomigo.com
    about: Check our documentation for guides and API references
  - name: Status Page
    url: https://status.aprendecomigo.com
    about: Check the current status of our services