name: Feature Request
description: Suggest a new feature or enhancement for the Aprende Comigo platform
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We're always looking to improve the platform based on user feedback.

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Student Management
        - Teacher Tools
        - Payment & Billing
        - Scheduling & Calendar
        - Communication & Messaging
        - Analytics & Reporting
        - School Administration
        - Parent Portal
        - Real-time Classroom
        - Mobile App
        - API Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: primary_stakeholder
    attributes:
      label: Primary Stakeholder
      description: Who would benefit most from this feature?
      multiple: true
      options:
        - School Owners
        - Teachers
        - Students
        - Parents
        - System Administrators
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: "Currently, users struggle with... because..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: "I would like to see a feature that..."
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: Describe how different users would use this feature
      placeholder: |
        As a [user type], I want to [action] so that [benefit]
        
        Example:
        As a teacher, I want to bulk upload student grades so that I can save time on data entry
    validations:
      required: false

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How would we measure the success of this feature?
      placeholder: |
        - Reduced time to complete [task] by X%
        - Increased user engagement by Y%
        - Decreased support tickets related to Z

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature for your operations?
      options:
        - Critical - Cannot operate effectively without it
        - High - Significantly impacts daily operations
        - Medium - Would improve efficiency
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Currently we work around this by..."

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, wireframes, or examples from other platforms
      placeholder: "Drag and drop images here or provide links to similar features"

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical requirements or constraints to consider?
      placeholder: "This feature would need to integrate with..."

  - type: input
    id: estimated_users
    attributes:
      label: Estimated Users Affected
      description: How many users would benefit from this feature?
      placeholder: "100+ teachers across 5 schools"

  - type: checkboxes
    id: implementation_scope
    attributes:
      label: Implementation Scope
      description: Where should this feature be available?
      options:
        - label: Web Application
        - label: iOS App
        - label: Android App
        - label: Admin Dashboard
        - label: API Endpoint

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that would help us understand this request?