name: Security Vulnerability
description: Report a security vulnerability - For critical issues, please email security@aprendecomigo.com
title: "[SECURITY] "
labels: ["security", "priority-critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities that could immediately impact users, please DO NOT create a public issue. Instead, email us at security@aprendecomigo.com
        
        This form is for lower-severity security concerns that can be discussed publicly.

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security issue have you found?
      options:
        - Authentication/Authorization Issue
        - Data Exposure
        - Input Validation
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Cross-Site Request Forgery (CSRF)
        - Session Management
        - Information Disclosure
        - Configuration Issue
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity_level
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical - Immediate risk to user data/system
        - High - Significant security risk
        - Medium - Moderate security risk
        - Low - Minor security concern
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue you've discovered
      placeholder: "I discovered that user sessions are not properly invalidated when..."
    validations:
      required: true

  - type: textarea
    id: affected_components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - Authentication system
        - User profile API endpoints
        - Session management
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be exploited? (Be responsible - provide enough detail to verify, not to exploit)
      placeholder: |
        1. Log in as any user
        2. Navigate to profile settings
        3. Modify the request to...
        4. Observe unauthorized access
    validations:
      required: true

  - type: textarea
    id: impact_assessment
    attributes:
      label: Potential Impact
      description: What could an attacker do with this vulnerability?
      placeholder: |
        An attacker could potentially:
        - Access other users' data
        - Bypass authentication
        - Modify payment information
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept if available (be responsible)
      render: shell

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: How would you recommend fixing this vulnerability?
      placeholder: "Implement proper input validation on..."

  - type: input
    id: affected_versions
    attributes:
      label: Affected Versions
      description: Which versions of the platform are affected?
      placeholder: "v2.1.0 - v2.3.5"

  - type: checkboxes
    id: user_data_impact
    attributes:
      label: Data Impact
      description: What type of data could be compromised?
      options:
        - label: Personal Information (PII)
        - label: Payment/Financial Data
        - label: Student Records
        - label: Authentication Credentials
        - label: School Administrative Data
        - label: Session Tokens
        - label: API Keys/Secrets

  - type: checkboxes
    id: discovery_method
    attributes:
      label: Discovery Method
      options:
        - label: Found during normal use
        - label: Security testing/audit
        - label: Code review
        - label: Automated scanning
        - label: Reported by user

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other information that might be helpful

  - type: checkboxes
    id: confirmation
    attributes:
      label: Responsible Disclosure
      description: Please confirm
      options:
        - label: I have not exploited this vulnerability beyond verification
          required: true
        - label: I will not share this information publicly until fixed
          required: true
        - label: For critical issues, I understand I should email security@aprendecomigo.com instead
          required: true