name: User Experience Issue
description: Report UX/UI issues, accessibility problems, or usability concerns
title: "[UX] "
labels: ["ux", "ui", "needs-design-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve the user experience of the Aprende Comigo platform!

  - type: dropdown
    id: ux_category
    attributes:
      label: UX Category
      description: What type of UX issue is this?
      options:
        - Visual Design
        - Navigation/Flow
        - Accessibility
        - Mobile Responsiveness
        - Information Architecture
        - Interaction Design
        - Content/Copy
        - Onboarding
        - Error Handling
        - Loading States
        - Consistency
        - Other
    validations:
      required: true

  - type: dropdown
    id: affected_platform
    attributes:
      label: Affected Platform
      description: Where does this UX issue occur?
      multiple: true
      options:
        - Web Desktop
        - Web Mobile
        - iOS App
        - Android App
        - All Platforms
    validations:
      required: true

  - type: dropdown
    id: affected_users
    attributes:
      label: Primary Users Affected
      description: Which users are most impacted by this issue?
      multiple: true
      options:
        - School Owners
        - Teachers
        - Students
        - Parents
        - New Users
        - All Users
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the UX problem you're experiencing
      placeholder: "Users are confused when trying to schedule a class because..."
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: What happens currently?
      placeholder: "Currently, users have to click through 5 different screens to..."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Users should be able to complete this task in 2 steps..."
    validations:
      required: true

  - type: textarea
    id: user_feedback
    attributes:
      label: User Feedback
      description: Any specific feedback from users about this issue?
      placeholder: |
        "Three teachers mentioned they couldn't find the export button"
        "Parents are confused about how to approve payments"

  - type: dropdown
    id: severity
    attributes:
      label: Impact Severity
      description: How severely does this impact user experience?
      options:
        - Critical - Users cannot complete essential tasks
        - High - Significant frustration or confusion
        - Medium - Minor confusion or extra steps
        - Low - Cosmetic or preference issue
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Visual examples of the UX issue
      placeholder: "Drag and drop images or videos here"
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How would you improve this user experience?
      placeholder: |
        1. Add a clear CTA button on the dashboard
        2. Reduce steps from 5 to 2
        3. Add helpful tooltips
        4. Improve error messages

  - type: textarea
    id: design_mockups
    attributes:
      label: Design Mockups
      description: If you have design suggestions, share them here
      placeholder: "Attach wireframes, mockups, or sketches"

  - type: checkboxes
    id: accessibility_check
    attributes:
      label: Accessibility Considerations
      description: Check any accessibility issues present
      options:
        - label: Screen reader compatibility issue
        - label: Keyboard navigation problem
        - label: Color contrast insufficient
        - label: Missing alt text or labels
        - label: Touch targets too small
        - label: Missing focus indicators
        - label: No accessibility issue

  - type: dropdown
    id: device_specific
    attributes:
      label: Device/Screen Size
      description: Is this issue specific to certain devices or screen sizes?
      options:
        - All devices
        - Desktop only (>1024px)
        - Tablet only (768-1024px)
        - Mobile only (<768px)
        - Specific device model
    validations:
      required: false

  - type: textarea
    id: user_journey
    attributes:
      label: User Journey Context
      description: Describe the user's journey when they encounter this issue
      placeholder: |
        1. User logs in as teacher
        2. Navigates to student management
        3. Tries to bulk import students
        4. Gets confused by the import interface

  - type: input
    id: frequency
    attributes:
      label: Frequency of Issue
      description: How often do users encounter this?
      placeholder: "Daily, affects 80% of new teacher onboarding"

  - type: textarea
    id: competitive_examples
    attributes:
      label: Examples from Other Platforms
      description: How do other platforms handle this better?
      placeholder: "Google Classroom handles this by..."

  - type: checkboxes
    id: testing
    attributes:
      label: Testing
      options:
        - label: I have tested this with actual users
        - label: This is based on user complaints/feedback
        - label: This is based on analytics data
        - label: This is based on personal observation

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other context about this UX issue?