name: User Journey Design
description: Design and document a complete user flow for a specific feature or process
title: "[User Journey] "
labels: ["user-experience", "design", "user-journey"]
body:
  - type: markdown
    attributes:
      value: |
        ## Flow Overview
        
  - type: input
    id: flow_name
    attributes:
      label: Flow Name
      description: e.g., "Account Registration Flow", "Course Enrollment Flow"
      placeholder: Enter the name of the user flow
    validations:
      required: true
      
  - type: textarea
    id: user_goal
    attributes:
      label: User Goal
      description: What the user wants to achieve
      placeholder: Describe what the user is trying to accomplish
    validations:
      required: true
      
  - type: textarea
    id: business_goal
    attributes:
      label: Business Goal
      description: What you want to achieve
      placeholder: Describe the business objective
    validations:
      required: true
      
  - type: input
    id: entry_point
    attributes:
      label: Entry Point
      description: How user gets to this flow
      placeholder: e.g., "Landing page CTA", "Dashboard button"
    validations:
      required: true
      
  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How you'll know it worked
      placeholder: Define measurable success indicators
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## User Persona
        
  - type: textarea
    id: user_persona
    attributes:
      label: Primary User Persona
      description: Who is the main user for this flow?
      placeholder: |
        **User Type**: [e.g., New teacher, Returning student, Parent]
        **Context**: [When/why they're using this flow]
        **Tech Comfort**: [High/Medium/Low]
        **Device**: [Mobile/Desktop preference]
        **Pain Points**: [Current frustrations this flow should solve]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Design Principles
        
  - type: checkboxes
    id: design_principles
    attributes:
      label: Core Principles
      description: Select the principles that apply to this flow
      options:
        - label: "**Minimize cognitive load** - Keep each step simple"
        - label: "**Progressive disclosure** - Only show what's needed now"
        - label: "**Clear progress** - User knows where they are"
        - label: "**Easy exit/return** - User can leave and come back"
        - label: "**Mobile-first** - Works great on smallest screen"
        
  - type: textarea
    id: additional_principles
    attributes:
      label: Additional Principles
      description: Add any flow-specific design principles
      placeholder: List any additional principles specific to this user journey

  - type: markdown
    attributes:
      value: |
        ## Step-by-Step Flow Design
        
  - type: textarea
    id: flow_steps
    attributes:
      label: Flow Steps
      description: Design each step of the user journey
      placeholder: |
        ### Step 1: [Step Name]
        **User Intent**: [What brings them here]
        **User Provides**: [Data/decisions needed from user]
        **User Needs**: [Info/context to proceed]
        **Primary Action**: [Main button/action]
        **Screen Elements**: [Key UI components]
        **Success**: [How to move forward]
        
        ---
        
        ### Step 2: [Step Name]
        [Repeat for each step]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Alternative Paths & Edge Cases
        
  - type: textarea
    id: alternative_paths
    attributes:
      label: Alternative Paths
      description: Document different user paths and edge cases
      placeholder: |
        ### Path A: [e.g., "Social Login"]
        - **Trigger**: [User chooses social login]
        - **Steps**: [Different sequence]
        - **Rejoins main flow at**: [Step X]
        
        ### Path B: [e.g., "Existing User"]
        - **Trigger**: [Email already exists]
        - **Steps**: [Redirect to login]
        - **Alternative outcome**: [Different end state]
        
        ### Error Scenarios:
        - **Network failure**: [How to handle]
        - **Invalid input**: [Error messages & recovery]
        - **Service unavailable**: [Graceful degradation]

  - type: markdown
    attributes:
      value: |
        ## Content & Messaging
        
  - type: textarea
    id: content_strategy
    attributes:
      label: Content Strategy
      description: Define tone, key messages, and micro-copy
      placeholder: |
        **Tone & Voice**: [Friendly, professional, encouraging, etc.]
        
        **Key Messages by Step**:
        - **Step 1**: [Main message]
        - **Step 2**: [Main message]
        
        **Micro-copy**:
        - **Buttons**: [Specific action labels]
        - **Errors**: [Helpful, not blame-y]
        - **Success**: [Celebrate progress]

  - type: markdown
    attributes:
      value: |
        ## Technical & Implementation
        
  - type: textarea
    id: technical_requirements
    attributes:
      label: Technical Requirements
      description: Key technical considerations
      placeholder: |
        **Data**: [What's stored, when saved, incomplete flow handling]
        **Performance**: [Load time, auto-save, offline needs]
        **Security**: [Validation, privacy, transmission requirements]

  - type: markdown
    attributes:
      value: |
        ## Success Metrics & Validation
        
  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How will you measure and validate this flow?
      placeholder: |
        **Metrics**: Conversion rate, drop-off points, completion time, error rates
        
        **Validation Methods**: [Card sorting, prototyping, user testing, etc.]
        
        **Key Questions**: Does sequence feel logical? Any unnecessary steps? What causes abandonment?
        
  - type: checkboxes
    id: validation_methods
    attributes:
      label: Validation Approaches
      description: Select methods you'll use
      options:
        - label: "Card sorting - Test logical sequence"
        - label: "Paper prototype - Test before building"
        - label: "User testing - Validate with real users"
        - label: "Cognitive walkthrough - Expert review"

  - type: markdown
    attributes:
      value: |
        ## Implementation Notes
        
  - type: textarea
    id: design_decisions
    attributes:
      label: Design Decisions & Notes
      description: Document key decisions, alternatives, and additional considerations
      placeholder: |
        **Key Decisions**: [Decision + reasoning]
        **Alternatives Considered**: [Why rejected]
        **Still to Decide**: [Open questions]
        **Dependencies**: [Other features/teams needed]
        **Additional Notes**: [Context, constraints, etc.]