# Generated by Django 5.1.11 on 2025-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed for group classes', null=True, verbose_name='maximum participants'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata for the class', verbose_name='metadata'),
        ),
    ]
