# Generated by Django 5.1.11 on 2025-08-07 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_classschedule_max_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed at'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejected at'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rejected', 'Rejected')], default='scheduled', max_length=20, verbose_name='status'),
        ),
    ]
