# Generated by Django 5.1.11 on 2025-08-08 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_add_reminder_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classreminder',
            index=models.Index(fields=['scheduled_for', 'status'], name='scheduler_c_schedul_67d562_idx'),
        ),
        migrations.AddConstraint(
            model_name='classreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sent'])), fields=('class_schedule', 'reminder_type', 'recipient', 'communication_channel'), name='unique_reminder_per_recipient_channel'),
        ),
    ]
