# Generated by Django 5.1.7 on 2025-03-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                default="admin",
                max_length=20,
                verbose_name="user type",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_year",
                    models.CharField(max_length=50, verbose_name="school year"),
                ),
                ("birth_date", models.DateField(verbose_name="birth date")),
                (
                    "address",
                    models.TextField(
                        help_text="Street, number, postal code and location",
                        verbose_name="address",
                    ),
                ),
                (
                    "cc_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CC number"
                    ),
                ),
                (
                    "cc_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of CC front and back (only for in-person students)",
                        null=True,
                        upload_to="cc_photos/",
                        verbose_name="CC photo",
                    ),
                ),
                (
                    "calendar_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="calendar URL"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
