# Generated by Django 5.2.5 on 2025-09-14 07:32

from django.db import migrations


def set_first_student_added_for_existing_users(apps, schema_editor):
    """
    Set first_student_added=True for users who already have students.
    This handles the existing users when introducing the new verification task.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    StudentProfile = apps.get_model('accounts', 'StudentProfile')

    # Check if any students exist at all
    if StudentProfile.objects.exists():
        # If there are students, mark all existing users as having completed the task
        # since they were grandfathered in before this verification was required
        CustomUser.objects.all().update(first_student_added=True)


def reverse_set_first_student_added_for_existing_users(apps, schema_editor):
    """
    Reverse the migration by setting first_student_added=False for all users.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.all().update(first_student_added=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_first_student_added_field"),
    ]

    operations = [
        migrations.RunPython(
            set_first_student_added_for_existing_users,
            reverse_set_first_student_added_for_existing_users
        ),
    ]
