# Generated by Django 5.1.7 on 2025-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_user_type_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="calendar_url",
        ),
        migrations.AddField(
            model_name="student",
            name="calendar_iframe",
            field=models.TextField(blank=True, verbose_name="calendar iframe"),
        ),
    ]
