# Generated by Django 5.1.7 on 2025-04-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_student_calendar_url_student_calendar_iframe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Teacher's professional biography",
                        verbose_name="biography",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="specialty"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True,
                        help_text="Educational background and qualifications",
                        verbose_name="education",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        blank=True,
                        help_text="Available days and times for lessons",
                        verbose_name="availability",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Street, number, postal code and location",
                        verbose_name="address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teacher phone"
                    ),
                ),
                (
                    "calendar_iframe",
                    models.TextField(blank=True, verbose_name="calendar iframe"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
