# Generated by Django 5.2.5 on 2025-09-14 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_set_first_student_added_for_existing_users"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="accounts_cu_email_v_dd12f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="accounts_cu_phone_v_d0c099_idx",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="accounts_cu_first_s_7627ab_idx",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_student_added",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_verified",
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025, 9, 14, 8, 2, 1, 648157, tzinfo=datetime.timezone.utc
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
