# Generated by Django 5.1.11 on 2025-08-08 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_reminder_models'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['educational_system__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['name', 'email']},
        ),
        migrations.AlterModelOptions(
            name='educationalsystem',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Educational System', 'verbose_name_plural': 'Educational Systems'},
        ),
        migrations.AlterModelOptions(
            name='schoolinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='schoolinvitationlink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user__name', 'birth_date']},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='teacherinvitation',
            name='unique_active_teacher_invitation_per_school',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['educational_system', 'education_level'], name='accounts_co_educati_658084_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='accounts_co_code_781c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='accounts_co_name_672730_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='accounts_co_created_12114c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['name'], name='accounts_cu_name_eeb412_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verified'], name='accounts_cu_email_v_dd12f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['onboarding_completed'], name='accounts_cu_onboard_9c7ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_fcefff_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalsystem',
            index=models.Index(fields=['code'], name='accounts_ed_code_23b18c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalsystem',
            index=models.Index(fields=['name'], name='accounts_ed_name_a84045_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalsystem',
            index=models.Index(fields=['is_active'], name='accounts_ed_is_acti_095f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalsystem',
            index=models.Index(fields=['created_at'], name='accounts_ed_created_8099c4_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitation',
            index=models.Index(fields=['school', 'is_accepted', '-created_at'], name='accounts_sc_school__e69785_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitation',
            index=models.Index(fields=['email', 'is_accepted'], name='accounts_sc_email_a86abc_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitation',
            index=models.Index(fields=['token'], name='accounts_sc_token_8b9ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitation',
            index=models.Index(fields=['expires_at', 'is_accepted'], name='accounts_sc_expires_9f288a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitationlink',
            index=models.Index(fields=['school', 'role', 'is_active'], name='accounts_sc_school__537214_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitationlink',
            index=models.Index(fields=['token'], name='accounts_sc_token_b61623_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitationlink',
            index=models.Index(fields=['expires_at', 'is_active'], name='accounts_sc_expires_645a11_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolinvitationlink',
            index=models.Index(fields=['created_by', '-created_at'], name='accounts_sc_created_fb05ac_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user'], name='accounts_st_user_id_3ee8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['educational_system', 'school_year'], name='accounts_st_educati_049729_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['birth_date'], name='accounts_st_birth_d_b0f49b_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 8, 8, 16, 53, 11, 445119, tzinfo=datetime.timezone.utc)), ('is_accepted', False), ('status__in', ['pending', 'sent', 'delivered', 'viewed'])), fields=('email', 'school'), name='unique_active_teacher_invitation_per_school'),
        ),
    ]
