# Generated by Django 5.2.5 on 2025-09-10 10:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_audit_fields_to_studentprofile"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Guardian notification preferences (email, SMS, in-app)",
                        verbose_name="notification preferences",
                    ),
                ),
                (
                    "default_approval_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default purchase approval settings for all studentren",
                        verbose_name="default approval settings",
                    ),
                ),
                (
                    "email_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable email notifications for guardian alerts",
                        verbose_name="email notifications enabled",
                    ),
                ),
                (
                    "sms_notifications_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SMS notifications for guardian alerts",
                        verbose_name="SMS notifications enabled",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Street, number, postal code and location",
                        verbose_name="address",
                    ),
                ),
                (
                    "tax_nr",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="tax number"
                    ),
                ),
                (
                    "invoice",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to issue invoices for this guardian",
                        verbose_name="invoice",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "guardian Profile",
                "verbose_name_plural": "guardian Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="guardianstudentrelationship",
            options={
                "verbose_name": "guardian-student Relationship",
                "verbose_name_plural": "guardian-student Relationships",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.RemoveIndex(
            model_name="guardianstudentrelationship",
            name="accounts_pa_relatio_4f3c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianstudentrelationship",
            new_name="accounts_gu_guardia_87e86d_idx",
            old_name="accounts_gu_guardia_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianstudentrelationship",
            new_name="accounts_gu_student_ed0586_idx",
            old_name="accounts_gu_student_idx",
        ),
        migrations.RenameIndex(
            model_name="guardianstudentrelationship",
            new_name="accounts_gu_school__48d380_idx",
            old_name="accounts_gu_school_idx",
        ),
        migrations.RemoveField(
            model_name="guardianstudentrelationship",
            name="relationship_type",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="calendar_iframe",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="cc_number",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="cc_photo",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="financial_responsibility",
            field=models.CharField(
                choices=[
                    ("guardian", "Guardian Responsible"),
                    ("self", "Self Responsible"),
                    ("shared", "Shared Responsibility"),
                ],
                default="guardian",
                help_text="Who is financially responsible for this student's account",
                max_length=20,
                verbose_name="financial responsibility",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the student, special needs, etc.",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="guardianstudentrelationship",
            name="guardian",
            field=models.ForeignKey(
                help_text="Guardian user who manages the student account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentren_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="guardian",
            ),
        ),
        migrations.AlterField(
            model_name="guardianstudentrelationship",
            name="requires_purchase_approval",
            field=models.BooleanField(
                default=True,
                help_text="Whether guardian approval is required for purchases",
                verbose_name="requires purchase approval",
            ),
        ),
        migrations.AlterField(
            model_name="guardianstudentrelationship",
            name="requires_session_approval",
            field=models.BooleanField(
                default=True,
                help_text="Whether guardian approval is required for booking sessions",
                verbose_name="requires session approval",
            ),
        ),
        migrations.AlterField(
            model_name="guardianstudentrelationship",
            name="student",
            field=models.ForeignKey(
                help_text="Student user whose account is managed by the guardian",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="schoolinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_owner", "School Owner"),
                    ("school_admin", "School Administrator"),
                    ("teacher", "Teacher"),
                    ("school_staff", "School Staff"),
                    ("student", "Student"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="schoolinvitationlink",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_owner", "School Owner"),
                    ("school_admin", "School Administrator"),
                    ("teacher", "Teacher"),
                    ("school_staff", "School Staff"),
                    ("student", "Student"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="teacherinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_owner", "School Owner"),
                    ("school_admin", "School Administrator"),
                    ("teacher", "Teacher"),
                    ("school_staff", "School Staff"),
                    ("student", "Student"),
                    ("guardian", "Guardian"),
                ],
                default="teacher",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["phone_verified"], name="accounts_cu_phone_v_d0c099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["verification_required_after"],
                name="accounts_cu_verific_af0667_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            9,
                            10,
                            10,
                            11,
                            43,
                            735197,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Guardian of the student (null for adult students who are self-responsible)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.guardianprofile",
            ),
        ),
        migrations.DeleteModel(
            name="ParentProfile",
        ),
        migrations.AddIndex(
            model_name="guardianprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_gu_created_68ee24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianprofile",
            index=models.Index(
                fields=["email_notifications_enabled"],
                name="accounts_gu_email_n_81ed15_idx",
            ),
        ),
    ]
