# Generated by Django 5.2.5 on 2025-09-16 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_first_student_added_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Student's full name (used for guardian-only students without user accounts)",
                max_length=150,
                verbose_name="student name",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            9,
                            16,
                            15,
                            22,
                            45,
                            682215,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
