# Generated by Django 5.2.5 on 2025-09-10 14:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_guardian_field_to_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_profile", models.BooleanField(default=False)),
                ("can_view_grades", models.BooleanField(default=False)),
                ("can_view_attendance", models.BooleanField(default=False)),
                ("can_make_payment", models.BooleanField(default=False)),
                ("can_book_session", models.BooleanField(default=False)),
                ("can_cancel_session", models.BooleanField(default=False)),
                ("can_update_profile", models.BooleanField(default=False)),
                ("can_manage_budget", models.BooleanField(default=False)),
                ("can_view_financial", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="financial_responsibility",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("STUDENT_GUARDIAN", "Student + Guardian Accounts"),
                    ("ADULT_STUDENT", "Adult Student Only"),
                    ("GUARDIAN_ONLY", "Guardian Manages Student Data"),
                ],
                default="STUDENT_GUARDIAN",
                help_text="Defines who has accounts and manages this student",
                max_length=20,
                verbose_name="account type",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Student address (only for adult students)",
                verbose_name="address",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable email notifications for student alerts",
                verbose_name="email notifications enabled",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="invoice",
            field=models.BooleanField(
                default=False,
                help_text="Whether to issue invoices (only for adult students)",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sms_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable SMS notifications for student alerts",
                verbose_name="SMS notifications enabled",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="tax_nr",
            field=models.CharField(
                blank=True,
                help_text="Tax number (only for adult students)",
                max_length=20,
                verbose_name="tax number",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Guardian of the student (required for guardian-managed accounts)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.guardianprofile",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="User account for this student (null if guardian-only management)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            9,
                            10,
                            14,
                            55,
                            18,
                            689373,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
        migrations.AddField(
            model_name="studentpermission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentpermission",
            index=models.Index(
                fields=["student", "user"], name="accounts_st_student_a971e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpermission",
            index=models.Index(
                fields=["expires_at"], name="accounts_st_expires_0c91ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentpermission",
            unique_together={("student", "user")},
        ),
    ]
