# Generated by Django 5.2.5 on 2025-09-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0010_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="accounts_st_educati_232fe1_idx",
            old_name="accounts_st_educati_049729_idx",
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_owner", "School Owner"),
                    ("school_admin", "School Administrator"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="educational_system",
            field=models.CharField(
                choices=[("pt", "Portugal"), ("custom", "Custom")],
                default="pt",
                help_text="Educational system this student belongs to",
                max_length=20,
                verbose_name="educational system",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            9,
                            17,
                            13,
                            50,
                            56,
                            406185,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
