# Generated by Django 5.2.5 on 2025-09-17 09:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0010_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("email_verify", "Email Verification"),
                            ("phone_verify", "Phone Verification"),
                            ("signin_otp", "Signin OTP"),
                        ],
                        help_text="Type of verification this token is for",
                        max_length=20,
                        verbose_name="token type",
                    ),
                ),
                (
                    "token_value",
                    models.CharField(
                        help_text="Hashed token value for security",
                        max_length=255,
                        verbose_name="token value",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this token expires", verbose_name="expires at"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was successfully used",
                        null=True,
                        verbose_name="used at",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of failed verification attempts",
                        verbose_name="attempts",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum allowed attempts before token is locked",
                        verbose_name="max attempts",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "Verification Token",
                "verbose_name_plural": "Verification Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="VerificationCode",
        ),
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when email was verified",
                null=True,
                verbose_name="email verified at",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time user was active on the platform",
                verbose_name="last activity",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="E.164 format phone number for duplicate checking",
                max_length=20,
                verbose_name="normalized phone number",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when phone was verified",
                null=True,
                verbose_name="phone verified at",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_otp_method",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                default="email",
                help_text="User's preferred method for receiving OTP codes",
                max_length=10,
                verbose_name="preferred OTP method",
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_owner", "School Owner"),
                    ("school_admin", "School Administrator"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["email_verified_at"], name="accounts_cu_email_v_97f41d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["phone_verified_at"], name="accounts_cu_phone_v_ebda96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["phone_number_normalized"],
                name="accounts_cu_phone_n_ef6b3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["last_activity"], name="accounts_cu_last_ac_6ec725_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number_normalized", ""), _negated=True),
                fields=("phone_number_normalized",),
                name="unique_normalized_phone_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025, 9, 17, 9, 10, 2, 112849, tzinfo=datetime.timezone.utc
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
        migrations.AddField(
            model_name="verificationtoken",
            name="user",
            field=models.ForeignKey(
                help_text="User this token belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(
                fields=["user", "token_type", "expires_at"],
                name="accounts_ve_user_id_7e4e2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(
                fields=["token_value", "used_at"], name="accounts_ve_token_v_77786c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(
                fields=["expires_at", "used_at"], name="accounts_ve_expires_2b9380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(
                fields=["created_at"], name="accounts_ve_created_b10d22_idx"
            ),
        ),
    ]
