# Generated by Django 5.2.5 on 2025-09-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0011_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more",
        ),
        ("accounts", "0011_verificationtoken_delete_verificationcode_and_more"),
    ]

    operations = []
