# Generated by Django 5.2.5 on 2025-09-17 18:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_merge_20250917_1719"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="accounts_st_educati_049729_idx",
            old_name="accounts_st_educati_232fe1_idx",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="educational_system",
            field=models.ForeignKey(
                default=2,
                help_text="Educational system this student belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.educationalsystem",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025, 9, 17, 18, 37, 28, 79693, tzinfo=datetime.timezone.utc
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
