# Generated by Django 5.2.5 on 2025-09-26 12:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_migrate_existing_guardians_to_primary"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacherinvitation",
            name="unique_active_teacher_invitation_per_school",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="International phone number with country code (required for Student+Guardian accounts)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone_format",
                        message="Please enter a valid international phone number format (e.g., +351912345678)",
                        regex="^(\\+|00)[1-9]\\d{1,14}$",
                    )
                ],
                verbose_name="student phone number",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="school_year",
            field=models.CharField(
                help_text="School year within the educational system. Available choices defined in UnifiedSchoolYear enum.",
                max_length=50,
                verbose_name="school year",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2025,
                            9,
                            26,
                            12,
                            20,
                            39,
                            529214,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                    ("is_accepted", False),
                    ("status__in", ["pending", "sent", "delivered", "viewed"]),
                ),
                fields=("email", "school"),
                name="unique_active_teacher_invitation_per_school",
            ),
        ),
    ]
