"""
Constants for Scheduling Rules & Conflict Management - GitHub Issue #152

This module defines all constants used throughout the scheduling system
to avoid magic numbers and improve maintainability.
"""

# Time and Duration Constants
DEFAULT_SLOT_INTERVAL_MINUTES = 30
MAX_CLASS_DURATION_MINUTES = 480  # 8 hours
MAX_ACTUAL_DURATION_MINUTES = 600  # 10 hours for completion tracking
MIN_CLASS_DURATION_MINUTES = 15
DEFAULT_MINIMUM_NOTICE_HOURS = 2
DEFAULT_MINIMUM_NOTICE_MINUTES = 120  # 2 hours
DEFAULT_CANCELLATION_DEADLINE_HOURS = 2

# Buffer Time Defaults
DEFAULT_BUFFER_TIME_MINUTES = 15
DEFAULT_BUFFER_TIME_GROUP_MINUTES = 20
DEFAULT_BUFFER_TIME_TRIAL_MINUTES = 10

# Booking Limits
DEFAULT_TEACHER_MAX_DAILY_BOOKINGS = 8
DEFAULT_TEACHER_MAX_WEEKLY_BOOKINGS = 30
DEFAULT_STUDENT_MAX_DAILY_BOOKINGS = 3
DEFAULT_STUDENT_MAX_WEEKLY_BOOKINGS = 10

# Time Format Validation
TIME_FORMAT_DIGIT_COUNT = 2
HOUR_MIN = 0
HOUR_MAX = 23
MINUTE_MIN = 0
MINUTE_MAX = 59

# Time Boundaries
EARLIEST_CLASS_HOUR = 6  # 06:00
LATEST_CLASS_HOUR = 23  # 23:00

# Query Optimization
SCHEDULING_QUERY_BATCH_SIZE = 100
MAX_AVAILABILITY_DAYS_LOOKUP = 30

# Conversion Factors
MINUTES_TO_HOURS_CONVERSION = 60
SECONDS_TO_HOURS_CONVERSION = 3600
