# Generated by Django 5.1.7 on 2025-04-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scheduling", "0002_remove_classtype_default_duration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("package", "Package")],
                        max_length=20,
                        verbose_name="plan type",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "hours_included",
                    models.IntegerField(
                        default=0,
                        help_text="For package plans",
                        verbose_name="hours included",
                    ),
                ),
                (
                    "expiration_period",
                    models.IntegerField(
                        default=0,
                        help_text="Days until package expires",
                        verbose_name="expiration period",
                    ),
                ),
                (
                    "class_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_plans",
                        to="scheduling.classtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount paid"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="payment date")),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="For monthly plans",
                        null=True,
                        verbose_name="period start",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="For monthly plans",
                        null=True,
                        verbose_name="period end",
                    ),
                ),
                (
                    "hours_purchased",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="For package plans",
                        max_digits=10,
                        verbose_name="hours purchased",
                    ),
                ),
                (
                    "hours_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="For package plans",
                        max_digits=10,
                        verbose_name="hours used",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payments",
                        to="financials.paymentplan",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherCompensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="period start")),
                ("period_end", models.DateField(verbose_name="period end")),
                (
                    "hours_taught",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="hours taught"
                    ),
                ),
                (
                    "amount_owed",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount owed"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="payment date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "class_sessions",
                    models.ManyToManyField(
                        related_name="teacher_compensations",
                        to="scheduling.classsession",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
