repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  # TypeScript/JavaScript specific checks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.53.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-import@2.29.0
          - eslint-plugin-prettier@5.0.1
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-native@4.1.0
          - "@typescript-eslint/eslint-plugin@6.10.0"
          - "@typescript-eslint/parser@6.10.0"

  # Prettier formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css]
        additional_dependencies:
          - prettier@3.0.3

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type checking
        entry: npx typescript --noEmit
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false
        always_run: true

  # Jest tests
  - repo: local
    hooks:
      - id: jest-tests
        name: Run Jest tests
        entry: npx jest --bail --findRelatedTests
        language: system
        files: \.(ts|tsx)$
        pass_filenames: true
        stages: [commit-msg, post-commit]

  # Dependency checks
  - repo: local
    hooks:
      - id: npm-check
        name: Check for package.json issues
        entry: npx npm-check
        language: system
        files: package.json
        pass_filenames: false
        stages: [commit-msg, post-commit]
