# Headers for security, caching, and font loading
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://aprendecomigo.eu.pythonanywhere.com https://api.aprendecomigo.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Headers specifically for font files with long cache times
[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

# Headers for static assets
[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - always reroute requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
