const nativewind = require('nativewind/preset');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/*.{js,jsx,ts,tsx,mdx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [nativewind],
  safelist: [
    // Existing classes
    'gap-x-2', 'gap-y-6', 'pl-4', 'flex-wrap', 'mb-12', 'basis-[10%]',
    
    // Dynamic color patterns - Background classes
    'bg-red-50', 'bg-red-100', 'bg-red-200', 'bg-red-600',
    'bg-green-50', 'bg-green-100', 'bg-green-200', 'bg-green-600',
    'bg-blue-50', 'bg-blue-100', 'bg-blue-200', 'bg-blue-600',
    'bg-yellow-50', 'bg-yellow-100', 'bg-yellow-200', 'bg-yellow-600',
    'bg-orange-50', 'bg-orange-100', 'bg-orange-200', 'bg-orange-600',
    'bg-purple-50', 'bg-purple-100', 'bg-purple-200', 'bg-purple-600',
    'bg-indigo-50', 'bg-indigo-100', 'bg-indigo-200', 'bg-indigo-600',
    'bg-teal-50', 'bg-teal-100', 'bg-teal-200', 'bg-teal-600',
    'bg-gray-50', 'bg-gray-100', 'bg-gray-200', 'bg-gray-600',
    
    // Dynamic color patterns - Text classes
    'text-red-600', 'text-red-700',
    'text-green-600', 'text-green-700',
    'text-blue-600', 'text-blue-700',
    'text-yellow-600', 'text-yellow-700',
    'text-orange-600', 'text-orange-700',
    'text-purple-600', 'text-purple-700',
    'text-indigo-600', 'text-indigo-700',
    'text-teal-600', 'text-teal-700',
    'text-gray-600', 'text-gray-700',
    
    // Dynamic color patterns - Border classes
    'border-red-200', 'border-red-300',
    'border-green-200', 'border-green-300',
    'border-blue-200', 'border-blue-300',
    'border-yellow-200', 'border-yellow-300',
    'border-orange-200', 'border-orange-300',
    'border-purple-200', 'border-purple-300',
    'border-indigo-200', 'border-indigo-300',
    'border-teal-200', 'border-teal-300',
    'border-gray-200', 'border-gray-300',
    
    // Dynamic color patterns - Hover states
    'hover:bg-red-100', 'hover:bg-green-100', 'hover:bg-blue-100',
    'hover:bg-yellow-100', 'hover:bg-orange-100', 'hover:bg-purple-100',
    'hover:bg-indigo-100', 'hover:bg-teal-100', 'hover:bg-gray-100',
    
    // Custom theme colors with dynamic usage
    'text-primary-600', 'text-primary-700',
    'text-secondary-600', 'text-secondary-700',
    'text-tertiary-600', 'text-tertiary-700',
    'text-success-600', 'text-success-700',
    'text-error-600', 'text-error-700',
    'text-warning-600', 'text-warning-700',
    'text-info-600', 'text-info-700',
    
    // Landing page accent colors
    'text-accent-600', 'text-accent-700', 'bg-accent-600', 'border-accent-600',
    'text-accent-dark-600', 'text-accent-dark-700', 'bg-accent-dark-600', 'border-accent-dark-600',
    'text-accent-pink-600', 'text-accent-pink-700', 'bg-accent-pink-600', 'border-accent-pink-600',
    
    // Design System Patterns - Gradients
    'bg-gradient-primary', 'bg-gradient-accent', 'bg-gradient-accent-dark', 'bg-gradient-subtle',
    'bg-gradient-page', 'bg-gradient-section-light', 'bg-gradient-dark',
    
    // Design System Patterns - Glass Effects
    'glass-nav', 'glass-container', 'glass-light', 'glass-strong', 'glass-card',
    
    // Design System Patterns - Cards
    'hero-card', 'feature-card', 'feature-card-gradient',
    
    // Progress and status indicators
    'bg-primary-600', 'bg-secondary-600', 'bg-tertiary-600',
    'bg-success-600', 'bg-error-600', 'bg-warning-600', 'bg-info-600',
    
    // Animation classes that might be dynamic
    'animate-spin', 'animate-pulse',
    
    // Common dynamic utility classes
    'opacity-50', 'opacity-75', 'opacity-100',
    'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-3/4',
    'h-1/2', 'h-1/3', 'h-2/3', 'h-1/4', 'h-3/4',
  ],
  theme: {
    screens: {
      base: '0',
      xs: '400px',
      sm: '480px',
      md: '768px',
      lg: '992px',
      xl: '1280px',
    },
    extend: {
      colors: {
        primary: {
          0: 'var(--color-primary-0)',
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        secondary: {
          0: 'var(--color-secondary-0)',
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        tertiary: {
          50: 'var(--color-tertiary-50)',
          100: 'var(--color-tertiary-100)',
          200: 'var(--color-tertiary-200)',
          300: 'var(--color-tertiary-300)',
          400: 'var(--color-tertiary-400)',
          500: 'var(--color-tertiary-500)',
          600: 'var(--color-tertiary-600)',
          700: 'var(--color-tertiary-700)',
          800: 'var(--color-tertiary-800)',
          900: 'var(--color-tertiary-900)',
          950: 'var(--color-tertiary-950)',
        },
        error: {
          0: 'var(--color-error-0)',
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          950: 'var(--color-error-950)',
        },
        success: {
          0: 'var(--color-success-0)',
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          950: 'var(--color-success-950)',
        },
        warning: {
          0: 'var(--color-warning-0)',
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          950: 'var(--color-warning-950)',
        },
        info: {
          0: 'var(--color-info-0)',
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
          950: 'var(--color-info-950)',
        },
        typography: {
          0: 'var(--color-typography-0)',
          50: 'var(--color-typography-50)',
          100: 'var(--color-typography-100)',
          200: 'var(--color-typography-200)',
          300: 'var(--color-typography-300)',
          400: 'var(--color-typography-400)',
          500: 'var(--color-typography-500)',
          600: 'var(--color-typography-600)',
          700: 'var(--color-typography-700)',
          800: 'var(--color-typography-800)',
          900: 'var(--color-typography-900)',
          950: 'var(--color-typography-950)',
          white: '#FFFFFF',
          gray: '#D4D4D4',
          black: '#181718',
        },
        outline: {
          0: 'var(--color-outline-0)',
          50: 'var(--color-outline-50)',
          100: 'var(--color-outline-100)',
          200: 'var(--color-outline-200)',
          300: 'var(--color-outline-300)',
          400: 'var(--color-outline-400)',
          500: 'var(--color-outline-500)',
          600: 'var(--color-outline-600)',
          700: 'var(--color-outline-700)',
          800: 'var(--color-outline-800)',
          900: 'var(--color-outline-900)',
          950: 'var(--color-outline-950)',
        },
        background: {
          0: 'var(--color-background-0)',
          50: 'var(--color-background-50)',
          100: 'var(--color-background-100)',
          200: 'var(--color-background-200)',
          300: 'var(--color-background-300)',
          400: 'var(--color-background-400)',
          500: 'var(--color-background-500)',
          600: 'var(--color-background-600)',
          700: 'var(--color-background-700)',
          800: 'var(--color-background-800)',
          900: 'var(--color-background-900)',
          950: 'var(--color-background-950)',
          error: 'var(--color-background-error)',
          warning: 'var(--color-background-warning)',
          muted: 'var(--color-background-muted)',
          success: 'var(--color-background-success)',
          info: 'var(--color-background-info)',
          light: '#FBFBFB',
          dark: '#181719',
        },
        border: {
          0: 'var(--color-border-0)',
          50: 'var(--color-border-50)',
          100: 'var(--color-border-100)',
          200: 'var(--color-border-200)',
          300: 'var(--color-border-300)',
          400: 'var(--color-border-400)',
          500: 'var(--color-border-500)',
          600: 'var(--color-border-600)',
          700: 'var(--color-border-700)',
          800: 'var(--color-border-800)',
          900: 'var(--color-border-900)',
          950: 'var(--color-border-950)',
          error: 'var(--color-border-error)',
          warning: 'var(--color-border-warning)',
          muted: 'var(--color-border-muted)',
          success: 'var(--color-border-success)',
          info: 'var(--color-border-info)',
          light: '#FBFBFB',
          dark: '#181719',
        },
        accent: {
          0: 'var(--color-accent-0)',
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          950: 'var(--color-accent-950)',
        },
        'accent-dark': {
          0: 'var(--color-accent-dark-0)',
          50: 'var(--color-accent-dark-50)',
          100: 'var(--color-accent-dark-100)',
          200: 'var(--color-accent-dark-200)',
          300: 'var(--color-accent-dark-300)',
          400: 'var(--color-accent-dark-400)',
          500: 'var(--color-accent-dark-500)',
          600: 'var(--color-accent-dark-600)',
          700: 'var(--color-accent-dark-700)',
          800: 'var(--color-accent-dark-800)',
          900: 'var(--color-accent-dark-900)',
          950: 'var(--color-accent-dark-950)',
        },
        'accent-pink': {
          0: 'var(--color-accent-pink-0)',
          50: 'var(--color-accent-pink-50)',
          100: 'var(--color-accent-pink-100)',
          200: 'var(--color-accent-pink-200)',
          300: 'var(--color-accent-pink-300)',
          400: 'var(--color-accent-pink-400)',
          500: 'var(--color-accent-pink-500)',
          600: 'var(--color-accent-pink-600)',
          700: 'var(--color-accent-pink-700)',
          800: 'var(--color-accent-pink-800)',
          900: 'var(--color-accent-pink-900)',
          950: 'var(--color-accent-pink-950)',
        },
      },
      fontFamily: {
        roboto: ['Roboto', 'sans-serif'],
        brand: ['Kirang Haerang', 'system-ui'],
        primary: ['Work Sans', 'sans-serif'],
        body: ['Poppins', 'sans-serif'],
        mono: ['SF Mono', 'Monaco', 'Cascadia Code', 'monospace'],
      },
      fontWeight: {
        hairline: '100',
        extraBlack: '950',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-accent-dark': 'var(--gradient-accent-dark)',
        'gradient-subtle': 'var(--gradient-subtle)',
        'gradient-page': 'var(--gradient-page)',
        'gradient-section-light': 'var(--gradient-section-light)',
        'gradient-dark': 'var(--gradient-dark)',
      },
      backdropBlur: {
        'glass-nav': 'var(--glass-nav-blur)',
        'glass-container': 'var(--glass-container-blur)',
        'glass-light': 'var(--glass-light-blur)',
        'glass-strong': 'var(--glass-strong-blur)',
      },
      fontSize: {
        '2xs': '10px',
      },
      border: {
        2: '2px',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        // Glass Effect Utilities
        '.glass-nav': {
          'background': 'var(--glass-nav-bg)',
          'backdrop-filter': 'var(--glass-nav-blur)',
          '-webkit-backdrop-filter': 'var(--glass-nav-blur)',
          'border': '1px solid var(--glass-nav-border)',
          'box-shadow': '0 8px 32px rgba(0, 0, 0, 0.1)',
        },
        '.glass-container': {
          'background': 'var(--glass-container-bg)',
          'backdrop-filter': 'var(--glass-container-blur)',
          '-webkit-backdrop-filter': 'var(--glass-container-blur)',
          'border': '1px solid var(--glass-container-border)',
          'box-shadow': '0 4px 16px rgba(0, 0, 0, 0.05)',
        },
        '.glass-light': {
          'background': 'var(--glass-light-bg)',
          'backdrop-filter': 'var(--glass-light-blur)',
          '-webkit-backdrop-filter': 'var(--glass-light-blur)',
          'border': '1px solid var(--glass-light-border)',
        },
        '.glass-strong': {
          'background': 'var(--glass-strong-bg)',
          'backdrop-filter': 'var(--glass-strong-blur)',
          '-webkit-backdrop-filter': 'var(--glass-strong-blur)',
          'border': '1px solid var(--glass-strong-border)',
          'box-shadow': '0 12px 40px rgba(0, 0, 0, 0.15)',
        },
        
        // Card Effect Utilities
        '.hero-card': {
          'background': 'linear-gradient(135deg, #ffffff 0%, #f9fafb 100%)',
          'border': '1px solid #e5e7eb',
          'border-radius': '1.5rem',
          'box-shadow': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
          'transition': 'all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        },
        '.hero-card:hover': {
          'transform': 'translateY(-6px) scale(1.02)',
          'box-shadow': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        },
        
        '.feature-card': {
          'background': '#ffffff',
          'border': '1px solid #e5e7eb',
          'border-radius': '1.5rem',
          'box-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          'transition': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        },
        '.feature-card:hover': {
          'transform': 'translateY(-4px)',
          'box-shadow': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        },
        
        '.feature-card-gradient': {
          'background': 'var(--gradient-subtle)',
          'border': '1px solid #e2e8f0',
          'border-radius': '1.5rem',
          'transition': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        },
        '.feature-card-gradient:hover': {
          'transform': 'translateY(-4px)',
          'box-shadow': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
          'border-color': '#10b981',
        },
        
        '.glass-card': {
          'background': 'var(--glass-container-bg)',
          'backdrop-filter': 'var(--glass-container-blur)',
          '-webkit-backdrop-filter': 'var(--glass-container-blur)',
          'border': '1px solid var(--glass-container-border)',
          'border-radius': '1.5rem',
          'box-shadow': '0 8px 32px rgba(0, 0, 0, 0.1)',
        },
      };
      
      addUtilities(newUtilities, ['responsive', 'hover']);
    }
  ],
};
