# Generated by Django 5.2.5 on 2025-09-14 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="system_code",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for system-generated tasks",
                max_length=50,
                null=True,
                verbose_name="System Code",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "system_code"], name="tasks_task_user_id_848099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["system_code", "task_type"],
                name="tasks_task_system__39bfc4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("task_type", "system"), ("system_code__isnull", False)
                ),
                fields=("user", "system_code"),
                name="unique_user_system_task",
            ),
        ),
    ]
