# Generated by Django 5.2 on 2025-07-27 09:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours purchased by the student', max_digits=5, verbose_name='hours purchased')),
                ('hours_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours consumed by the student', max_digits=5, verbose_name='hours consumed')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance in euros', max_digits=6, verbose_name='balance amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('student', models.OneToOneField(help_text='Student who owns this account balance', on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'Student Account Balance',
                'verbose_name_plural': 'Student Account Balances',
                'ordering': ['-updated_at'],
            },
        ),
    ]
