# Generated by Django 5.2 on 2025-07-27 10:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_add_student_account_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('package', 'Package'), ('subscription', 'Subscription')], help_text='Type of transaction (package or subscription)', max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in euros', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20, verbose_name='payment status')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for this transaction', max_length=255, null=True, unique=True, verbose_name='Stripe payment intent ID')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID associated with this transaction', max_length=255, null=True, verbose_name='Stripe customer ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for packages (null for subscriptions)', null=True, verbose_name='expires at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data in JSON format', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('student', models.ForeignKey(help_text='Student who made this purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'Purchase Transaction',
                'verbose_name_plural': 'Purchase Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'payment_status'], name='finances_pu_student_7c93d8_idx'), models.Index(fields=['payment_status'], name='finances_pu_payment_4c82c2_idx'), models.Index(fields=['created_at'], name='finances_pu_created_2d08ff_idx'), models.Index(fields=['stripe_payment_intent_id'], name='finances_pu_stripe__34a676_idx'), models.Index(fields=['expires_at'], name='finances_pu_expires_d94582_idx')],
            },
        ),
    ]
