# Generated by Django 5.2 on 2025-07-27 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_purchase_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_consumed', models.DecimalField(decimal_places=2, help_text='Actual hours consumed during the session', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='hours consumed')),
                ('hours_originally_reserved', models.DecimalField(decimal_places=2, help_text='Hours originally reserved/scheduled for the session', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='hours originally reserved')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the consumption was recorded', verbose_name='consumed at')),
                ('is_refunded', models.BooleanField(default=False, help_text='Whether this consumption has been refunded', verbose_name='is refunded')),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for the refund (if applicable)', verbose_name='refund reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_session', models.OneToOneField(help_text='The class session for which hours were consumed', on_delete=django.db.models.deletion.CASCADE, related_name='hour_consumption', to='finances.classsession', verbose_name='class session')),
                ('purchase_transaction', models.ForeignKey(help_text='Original purchase transaction from which hours were consumed', on_delete=django.db.models.deletion.CASCADE, related_name='hour_consumptions', to='finances.purchasetransaction', verbose_name='purchase transaction')),
                ('student_account', models.ForeignKey(help_text='Student account that this consumption is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='hour_consumptions', to='finances.studentaccountbalance', verbose_name='student account')),
            ],
            options={
                'verbose_name': 'Hour Consumption',
                'verbose_name_plural': 'Hour Consumptions',
                'ordering': ['-consumed_at'],
                'indexes': [models.Index(fields=['student_account', 'consumed_at'], name='finances_ho_student_a9dee8_idx'), models.Index(fields=['class_session'], name='finances_ho_class_s_5c7f2c_idx'), models.Index(fields=['purchase_transaction'], name='finances_ho_purchas_1878ba_idx'), models.Index(fields=['is_refunded'], name='finances_ho_is_refu_b228d2_idx')],
            },
        ),
    ]
