# Generated by Django 5.1.11 on 2025-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_allow_null_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='status'),
        ),
    ]
