# Generated by Django 5.2 on 2025-07-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_add_pricing_plan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricingplan',
            new_name='finances_pr_is_acti_d5e588_idx',
            old_name='finances_pr_is_acti_539f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingplan',
            new_name='finances_pr_plan_ty_be4255_idx',
            old_name='finances_pr_plan_ty_bc9f6c_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingplan',
            new_name='finances_pr_is_feat_dab09e_idx',
            old_name='finances_pr_is_feat_e4c5f8_idx',
        ),
        migrations.AlterField(
            model_name='hourconsumption',
            name='class_session',
            field=models.ForeignKey(help_text='The class session for which hours were consumed', on_delete=django.db.models.deletion.CASCADE, related_name='hour_consumptions', to='finances.classsession', verbose_name='class session'),
        ),
        migrations.AddConstraint(
            model_name='hourconsumption',
            constraint=models.UniqueConstraint(fields=('student_account', 'class_session'), name='unique_student_session_consumption'),
        ),
    ]
