# Generated by Django 5.2 on 2025-08-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_add_receipt_and_payment_method_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receipt',
            new_name='finances_re_student_ad6876_idx',
            old_name='finances_re_student_2dd26d_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='finances_re_receipt_21cbaf_idx',
            old_name='finances_re_receipt_b7b1e4_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='finances_re_transac_16f606_idx',
            old_name='finances_re_transac_c3e2fb_idx',
        ),
        migrations.RenameIndex(
            model_name='storedpaymentmethod',
            new_name='finances_st_student_5a3cda_idx',
            old_name='finances_st_student_39b59a_idx',
        ),
        migrations.RenameIndex(
            model_name='storedpaymentmethod',
            new_name='finances_st_stripe__91a821_idx',
            old_name='finances_st_stripe__96ba8a_idx',
        ),
    ]
