# Generated by Django 5.2 on 2025-08-01 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_rename_finances_re_student_2dd26d_idx_finances_re_student_ad6876_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedpaymentmethod',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID associated with this payment method', max_length=255, null=True, verbose_name='Stripe customer ID'),
        ),
        migrations.AddIndex(
            model_name='storedpaymentmethod',
            index=models.Index(fields=['stripe_customer_id'], name='finances_st_stripe__74170f_idx'),
        ),
    ]
