# Generated by Django 5.2 on 2025-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_add_parent_purchase_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(help_text='Unique Stripe event identifier', max_length=255, unique=True, verbose_name='Stripe event ID')),
                ('event_type', models.CharField(help_text='Type of Stripe webhook event (e.g., payment_intent.succeeded)', max_length=100, verbose_name='event type')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='received', help_text='Current processing status of the webhook event', max_length=20, verbose_name='status')),
                ('payload', models.JSONField(help_text='Complete webhook event payload from Stripe', verbose_name='payload')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the event was successfully processed', null=True, verbose_name='processed at')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times processing has been retried', verbose_name='retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='finances_we_stripe__eee95d_idx'), models.Index(fields=['event_type', 'status'], name='finances_we_event_t_6a4c2e_idx'), models.Index(fields=['status', 'retry_count'], name='finances_we_status_92d2ae_idx'), models.Index(fields=['created_at'], name='finances_we_created_f52b4d_idx'), models.Index(fields=['processed_at'], name='finances_we_process_3ad47e_idx')],
            },
        ),
    ]
