# Generated by Django 5.1.11 on 2025-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_course_options_alter_customuser_options_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familybudgetcontrol',
            options={'ordering': ['-created_at'], 'verbose_name': 'Family Budget Control', 'verbose_name_plural': 'Family Budget Controls'},
        ),
        migrations.AddIndex(
            model_name='familybudgetcontrol',
            index=models.Index(fields=['created_at'], name='finances_fa_created_fc3e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='familybudgetcontrol',
            index=models.Index(fields=['is_active', '-created_at'], name='finances_fa_is_acti_8b7ad3_idx'),
        ),
    ]
