# Generated by Django 5.1.11 on 2025-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_familybudgetcontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Unique receipt identifier', max_length=50, null=True, unique=True, verbose_name='receipt number'),
        ),
    ]
