# Generated by Django 5.2.5 on 2025-09-11 09:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0010_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more",
        ),
        ("finances", "0002_rename_parent_to_guardian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="familybudgetcontrol",
            new_name="finances_fa_guardia_dad354_idx",
            old_name="finances_fa_guardian_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaseapprovalrequest",
            new_name="finances_pu_guardia_385cac_idx",
            old_name="finances_pu_guardian_status_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaseapprovalrequest",
            new_name="finances_pu_guardia_d82767_idx",
            old_name="finances_pu_guardian_rel_idx",
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="auto_approval_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Maximum amount that can be automatically approved without guardian intervention",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="auto approval threshold",
            ),
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="guardian_student_relationship",
            field=models.OneToOneField(
                help_text="The guardian-student relationship this budget control applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_control",
                to="accounts.guardianstudentrelationship",
                verbose_name="guardian-student relationship",
            ),
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="monthly_budget_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount student can spend per month (null for no limit)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="monthly budget limit",
            ),
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="require_approval_for_packages",
            field=models.BooleanField(
                default=True,
                help_text="Whether guardian approval is required for purchasing hour packages",
                verbose_name="require approval for packages",
            ),
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="require_approval_for_sessions",
            field=models.BooleanField(
                default=True,
                help_text="Whether guardian approval is required for booking individual sessions",
                verbose_name="require approval for sessions",
            ),
        ),
        migrations.AlterField(
            model_name="familybudgetcontrol",
            name="weekly_budget_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount student can spend per week (null for no limit)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="weekly budget limit",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseapprovalrequest",
            name="guardian",
            field=models.ForeignKey(
                help_text="Guardian who needs to approve the purchase",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="guardian",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseapprovalrequest",
            name="guardian_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes from the guardian about their decision",
                verbose_name="guardian notes",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseapprovalrequest",
            name="guardian_student_relationship",
            field=models.ForeignKey(
                help_text="The guardian-student relationship this request is under",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="accounts.guardianstudentrelationship",
                verbose_name="guardian-student relationship",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseapprovalrequest",
            name="responded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the guardian responded to the request",
                null=True,
                verbose_name="responded at",
            ),
        ),
    ]
