# Generated by Django 5.2.5 on 2025-08-21 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_alter_classsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachercompensationrule",
            name="effective_from",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Date from which this rule is effective",
                verbose_name="effective from",
            ),
        ),
    ]
