name: Deploy Staging to Netlify

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend-ui/**'
  workflow_dispatch: # Manual trigger

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-ui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build website (staging)
        run: npm run build:web:staging
        env:
          EXPO_PUBLIC_ENV: staging

      - name: Deploy to Netlify (staging)
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './frontend-ui/dist'
          production-branch: develop
          deploy-message: "Deploy from GitHub Actions (Staging)"
          alias: staging
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
