name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Deploy to PythonAnywhere
        env:
          # Required API credentials
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_DOMAIN: ${{ secrets.PA_DOMAIN }}
          # The API host - should be EITHER eu.pythonanywhere.com OR www.pythonanywhere.com
          PA_HOST: ${{ secrets.PA_HOST }}
          # Deployment configuration
          PA_VIRTUALENV_PATH: ${{ secrets.PA_VIRTUALENV_PATH }}
          PA_SOURCE_DIR: ${{ secrets.PA_SOURCE_DIR }}
        run: |
          python backend/scripts/deploy_to_pythonanywhere.py
