# Generated by Django 5.1.11 on 2025-08-07 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_classschedule_cancelled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='actual duration in minutes'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this class as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='completion_notes',
            field=models.TextField(blank=True, verbose_name='completion notes'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='marked no-show at'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='no_show_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this class as no-show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_show_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='no_show_reason',
            field=models.TextField(blank=True, verbose_name='no-show reason'),
        ),
    ]
