# Generated by Django 5.1.11 on 2025-08-08 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_teacherinvitation_unique_active_teacher_invitation_per_school_and_more'),
        ('scheduler', '0005_add_scheduling_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringclassschedule',
            name='student',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, help_text='Recurring schedule that generated this instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_instances', to='scheduler.recurringclassschedule'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled this recurring series', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_recurring_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='frequency_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10, verbose_name='frequency type'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants for group classes', null=True, verbose_name='maximum participants'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paused at'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='paused_by',
            field=models.ForeignKey(blank=True, help_text='User who paused this recurring series', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_recurring_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='recurringclassschedule',
            name='students',
            field=models.ManyToManyField(help_text='Students participating in this recurring class', related_name='recurring_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recurringclassschedule',
            index=models.Index(fields=['teacher', 'status', 'start_date'], name='scheduler_r_teacher_6a63f5_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringclassschedule',
            index=models.Index(fields=['school', 'status'], name='scheduler_r_school__51bfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringclassschedule',
            index=models.Index(fields=['frequency_type', 'status'], name='scheduler_r_frequen_c570eb_idx'),
        ),
    ]
